package cpsat.mock.scenario;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;

import com.pageobjects.Set5_Question5_Appspot_PF;
import com.testing.base.TestBase;

public class Set5_Question5_appspot extends TestBase {

	@Before
	public void init(){
		init("Chrome", "http://ata123456789123456789.appspot.com/");
	}
	
	@Test
	public void maintest() throws Exception{
		Set5_Question5_Appspot_PF app = new Set5_Question5_Appspot_PF(d);
		checkPageReady();
		d.findElement(By.xpath(app.firstXpath)).sendKeys("7");
		d.findElement(By.xpath(app.secondXpath)).clear();
		d.findElement(By.xpath(app.secondXpath)).sendKeys("4");
		d.findElement(By.xpath(app.checkbox)).click();
		d.findElement(By.xpath(app.CalculateButton)).click();
		String Actual = d.findElement(By.xpath(app.Result)).getAttribute("value");
		System.out.println(Actual);
		 int a =7;
		 int b = 4;
		int Expected = (7*7)-2*(7*4)+(4*4);
		System.out.println(Expected);
		int act =Integer.parseInt(Actual);
		
		if(act== Expected){
			System.out.println("The result value is indeed generated by the equation a2 – 2 * (a *b) + b2 ");
		}
		else{
			System.out.println("The result value is not  generated by the equation a2 – 2 * (a *b) + b2 ");
		}
		
	}
	
	@After
	public void cl(){
		terminate();
	}
}
